import type { Config } from "tailwindcss"

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e2e7ff",
        surface: "#faf8ff",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-container": "#ede0ff",
        "inverse-primary": "#d2bbff",
        "tertiary-container": "#905b00",
        "on-primary-fixed": "#25005a",
        "primary-fixed": "#eaddff",
        "surface-bright": "#faf8ff",
        "on-background": "#131b2e",
        "secondary-fixed": "#6ffbbe",
        error: "#ba1a1a",
        outline: "#7b7487",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffe1c0",
        "primary-container": "#7c3aed",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-container": "#eaedff",
        "surface-variant": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#4a4455",
        "outline-variant": "#ccc3d8",
        secondary: "#006c49",
        "on-primary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed-variant": "#5a00c6",
        "tertiary-fixed": "#ffddb8",
        tertiary: "#704500",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#2a1700",
        "inverse-surface": "#283044",
        "surface-tint": "#732ee4",
        "surface-container-highest": "#dae2fd",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed": "#002113",
        background: "#faf8ff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-container": "#00714d",
        "on-secondary-fixed-variant": "#005236",
        "secondary-container": "#6cf8bb",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb95f",
        primary: "#630ed4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px",
        base: "8px",
        xs: "4px",
        "margin-desktop": "auto",
        gutter: "24px",
        md: "24px",
        lg: "48px",
        "margin-mobile": "16px",
        sm: "12px",
      },
      fontFamily: {
        "headline-md": ["Montserrat"],
        "headline-lg": ["Montserrat"],
        "label-sm": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "display-lg-mobile": ["Montserrat"],
        "body-lg": ["Montserrat"],
        "body-md": ["Montserrat"],
        "label-lg": ["Montserrat"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config
